SELECT * FROM BOOKLIST;

UPDATE booklist SET inprice = 20000 WHERE subject = '테스트2';

CREATE TABLE TESTFOR(
	num NUMBER(20),
	name VARCHAR2(30),
	CONSTRAINT test_pk PRIMARY KEY(num)
);

DROP TABLE TESTFOR;