-- SQL

-- TABLE 
-- 열 field 속성 attribute
-- 행 Record 튜플

-- SQL Structured Query Language : 관계형 데이터베이스 관리 시스템 RDBMS

-- DDL DML DCL

-- DDL CREATE ALTER DROP
-- DML INSERT UPDATE DELETE SELECT
-- DCL GRANT REBOKE

-- PRIMARY KEY 기본키

-- FOREIGN KEY 외래키

-- DDL Data Definition Language 데이터 정의어

DROP TABLE TESTFOR1 purge;

CREATE TABLE TESTFOR1(
	num1 NUMBER(10) NOT NULL,
	name1 VARCHAR2(20) NOT NULL,
	birth1 DATE,
	age1 NUMBER(10),
	gender1 VARCHAR2(10),
	position1 VARCHAR2(100) DEFAULT 'vocal',
	CONSTRAINT testnum_pk PRIMARY KEY(num1)
);

SELECT * FROM TESTFOR1;

DROP TABLE TESTFOR2 purge;

CREATE TABLE TESTFOR2(
	num2 NUMBER(10) NOT NULL,
	name2 VARCHAR2(20) NOT NULL,
	birth2 DATE,
	age2 NUMBER(10),
	gender2 VARCHAR2(10),
	position2 VARCHAR2(100) DEFAULT 'vocal',
	CONSTRAINT testnum2_pk2 PRIMARY KEY(num2)
);

SELECT * FROM TESTFOR2;

DROP TABLE TESTFORLIST purge;

CREATE TABLE TESTFORLIST(
	list_date DATE DEFAULT SYSDATE,
	list_idx NUMBER(5) NOT NULL,
	list_num1 NUMBER(5) NOT NULL,
	list_num2 NUMBER(5) NOT NULL,
	count NUMBER(5),
	
	CONSTRAINT list_pk PRIMARY KEY(list_date, list_idx),
	CONSTRAINT list_fk1 FOREIGN KEY(list_num1) REFERENCES TESTFOR1(num1),
	CONSTRAINT list_fk2 FOREIGN KEY(list_num2) REFERENCES TESTFOR2(num2)
);

SELECT * FROM TESTFORLIST;

-- TABLE field 수정
ALTER TABLE TESTFOR1 RENAME COLUMN name1 TO name;
ALTER TABLE TESTFOR1 RENAME COLUMN name TO name1;

SELECT * FROM TESTFOR1;

ALTER TABLE TESTFOR1 MODIFY age1 VARCHAR2(20);
ALTER TABLE TESTFOR2 MODIFY age2 VARCHAR2(20);

ALTER TABLE TESTFOR1 ADD grade VARCHAR2(20);
ALTER TABLE TESTFOR1 RENAME COLUMN grade TO grade1;
ALTER TABLE TESTFOR2 ADD grade2 VARCHAR2(20);

ALTER TABLE TESTFOR1 ADD test01 NUMBER(5);
ALTER TABLE TESTFOR1 DROP COLUMN test01;

ALTER TABLE TESTFORLIST DROP CONSTRAINT list_fk1;
ALTER TABLE TESTFORLIST ADD CONSTRAINT list_fk1 FOREIGN KEY(list_num1) REFERENCES TESTFOR1(num1);

ALTER TABLE TESTFOR1 ADD CONSTRAINT check_gender CHECK(gender1 IN('F', 'M'));
ALTER TABLE TESTFOR2 ADD CONSTRAINT check_gender2 CHECK(gender2 IN('F', 'M'));

ALTER TABLE TESTFOR1 ADD CONSTRAINT check_age1 CHECK(age1 < 100);
ALTER TABLE TESTFOR2 ADD CONSTRAINT check_age2 CHECK(age2 < 100);

SELECT * FROM TESTFOR1;
SELECT * FROM TESTFOR2;

-- 05 DDL ALTER 154

DROP TABLE ORDERS3
CREATE TABLE ORDERS3(
	order_id NUMBER(12, 0),
	order_date DATE,
	order_mode VARCHAR2(8),
	customer_id NUMBER(6, 0),
	order_status NUMBER(2, 0),
	order_total NUMBER(8, 2) DEFAULT 0,
	sales_rep_id NUMBER(6, 0),
	promotion_id NUMBER(6, 0),
	CONSTRAINT pk_order PRIMARY KEY(order_id),
	CONSTRAINT ch_order_mode CHECK(order_mode IN('direct', 'online'))
);

SELECT * FROM ORDERS3;

ALTER TABLE ORDERS3 RENAME COLUMN customer_id TO customer_number;

ALTER TABLE ORDERS3 ADD CONSTRAINT pro_check CHECK(promotion_id BETWEEN 10000 AND 99999);

CREATE TABLE ORDERS3COPY AS SELECT * FROM ORDERS3;


SELECT * FROM ORDERS3COPY;

DROP TABLE ORDERS3COPY;

